# Generated by Django 3.2.10 on 2023-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpr', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=4)),
            ],
        ),
    ]
