# Generated by Django 3.2.10 on 2023-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='max_withdrawal',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atm',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
