# Generated by Django 3.2.10 on 2023-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atm_location', models.CharField(max_length=200)),
            ],
        ),
    ]
